name: Send request to azure functions regularly to prevent cold start

on:
  schedule:
  - cron: "0/5 22-23,0-11 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - name: curl
      env:
        URL: https://welstory.azurewebsites.net/api/getcourse
      run: |
        curl $URL